version: "3.8"

services:
  techgear-db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - techgear_pg_storage:/var/lib/postgresql/data

  techgear-server:
    image: ydvankit/techgear-server:latest
    restart: always
    build: .
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - techgear_server_storage:/app/data
    depends_on:
      - techgear-db
    environment:
      - DATABASE_HOST=techgear-db
    env_file:
      - .env

volumes:
  techgear_pg_storage:
  techgear_server_storage:
