export const CONSTANTS = {
  MESSAGES: {
    USER_ALREADY_EXISTS: "User already exists",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_NOT_FOUND: "User not found",
    USER_CREATED: "User created",
    USER_LOGGED_IN: "User logged in",
    USER_LOGGED_OUT: "User logged out",
    INTERNAL_SERVER_ERROR: "Internal server error",
    ROUTE_NOT_FOUND: "Route not found",
    USER_LOGIN_REQUIRED: "User login required",
    FILE_NOT_FOUND: "File not found",
    PRODUCT_CREATED: "Product created",
    PRODUCT_FOUND: "Product found",
    PRODUCT_UPDATED: "Product updated",
    PRODUCT_DELETED: "Product deleted",
    PRODUCT_NOT_FOUND: "Product not found",
    RATING_ADDED: "Rating added",
    RATING_FOUND: "Rating found",
    RATING_ALREADY_EXISTS: "Rating already exists",
    ADDRESS_ADDED: "Address added",
    ADDRESS_DELETED: "Address deleted",
    ADDRESS_UPDATED: "Address updated",
    ADDRESS_FOUND: "Address found",
    ORDER_PLACED: "Order placed",
    ORDER_UPDATED: "Order updated",
    ORDER_FOUND: "Order found",
    ORDERS_FOUND: "Orders found",
    ORDER_DELETED: "Order deleted",
    ORDER_NOT_FOUND: "Order not found",
    MISSING_FIELDS: "Missing fields",
  },
};
