export const CONSTANTS = {
  MESSAGES: {
    USER_ALREADY_EXISTS: "User already exists",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_NOT_FOUND: "User not found",
    USER_CREATED: "User created",
    USER_LOGGED_IN: "User logged in",
    USER_LOGGED_OUT: "User logged out",
    INTERNAL_SERVER_ERROR: "Internal server error",
    ROUTE_NOT_FOUND: "Route not found",
    USER_LOGIN_REQUIRED: "User login required",
    FILE_NOT_FOUND: "File not found",
    PRODUCT_CREATED: "Product created",
    PRODUCT_FOUND: "Product found",
    PRODUCT_UPDATED: "Product updated",
    PRODUCT_DELETED: "Product deleted",
    PRODUCT_NOT_FOUND: "Product not found",
    MISSING_FIELDS: "Missing fields",
  },
};
